DROP TABLE IF EXISTS prices;

CREATE TABLE PRICES (
    PRICE_ID LONG AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID LONG NOT NULL,
    PRIORITY SMALLINT NOT NULL,
    PRICE DOUBLE NOT NULL,
    CURR VARCHAR(3) NOT NULL
);






  


